import NavMenu from "./NavMenu";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function MainLayout({ children }) {
    return (
        <html lang="en">
            <body className="">
                <NavMenu />
                {children}
            </body>
        </html>
    );
}
