import DashboardLayout from "@/components/DashboardLayout";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function MainDashboard({ children }) {
    return (
        <html lang="en">
            <body className="px-5 mt-5">
                <div className="flex">
                    <div className="w-1/4 pt-3">Mehedi</div>
                    <div className="w-3/4">
                        <DashboardLayout />
                        {children}
                    </div>
                </div>
            </body>
        </html>
    );
}
